baseurl = "/"
languageCode = "en"
title = "tail -f /var/log/buddyspike"
theme = "hemingway2"
copyright = "&copy; <a href=\"https://github.com/buddyspike\">buddyspike</a> 2017"
disqusShortname = "buddyspike"
googleAnalytics = "UA-57052137-3"
description = "Random notes of buddyspike."
keywords = ["buddyspike", "blog"]

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile" ] 

[[params.social]]
url = "https://github.com/buddyspike"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/buddyspike28"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"