baseurl = "/"
theme = "hugo-geo"
relativeURLs = false
languageCode = "en-us"
title = "Random thoughts from buddyspike"
disqusShortname = "buddyspike"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = false
	favicon = "/img/me.png"
	analytics = "UA-57052137-3"
	email = "buddyspike@geeksdiary.com"

	# profilepic = "img/me.png"
	
	title = "buddyspike"
	header = "tail -f /var/log/buddyspike"

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/buddyspike"
	[[params.socialbuttons]]
	faicon = "twitter"
	url = "https://twitter.com/buddyspike28"

	[[params.navlinks]]
	name = "About"
	url = "about"
	
	[[params.navlinks]]
	name = "Blog"
	url = ""